// <auto-generated />
using System;
using FODailyChallenges.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FODailyChallenges.Migrations
{
    [DbContext(typeof(ChallengesDBContext))]
    [Migration("20250620182955_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FODailyChallenges.Models.ChallengeResolution", b =>
                {
                    b.Property<Guid>("ResolutionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ChallengeID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ResolutionLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ResolutionQuantity")
                        .HasColumnType("int");

                    b.HasKey("ResolutionID");

                    b.ToTable("Resolution");
                });

            modelBuilder.Entity("FODailyChallenges.Models.DailyChallenge", b =>
                {
                    b.Property<Guid>("ChallengeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChallengeText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ChallengeType")
                        .HasColumnType("int");

                    b.HasKey("ChallengeID");

                    b.ToTable("Challenge");
                });
#pragma warning restore 612, 618
        }
    }
}
